docker_compose/django/app/app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView

from users import views as user_views
from tinyurl import views as tiny_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="pages/index.html"), name="home"),
    path("api/tiny/", include("tinyurl.urls")),
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("<short_url>/", tiny_views.get_original, name="get_original"),
    path("tiny/", tiny_views.TinyUrlListView.as_view(), name="tiny-list"),
    path("tiny/create/", tiny_views.TinyUrlCreateView.as_view(), name="tiny-create"),
]

docker_compose/django/app/tinyurl/urls.py
from django.urls import path

from .apis import views

app_name = "tinyurl"

urlpatterns = [
    path("original/", views.UrlDetailView.as_view(), name="original_api"),
    path("tinyurl/", views.UrlCreateView.as_view(), name="tinyurl_api"),
]

docker_compose/django/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <div class="navbar-nav mr-auto">
            <a class="navbar-brand mr-4" href="{% url 'home' %}">Home</a>
          </div>
          <div class="navbar-nav">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'tinyurl:tiny-create' %}">New TinyURL</a>
              <a class="nav-item nav-link" href="{% url 'tinyurl:tiny-list' %}">URL List</a>
              <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                </button>
              </div>
            {% endfor %}
          {% endif %}
          {% block content %} {% endblock content %}
        </div>
      </div>
    </main>

    <div>
      {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </body>
</html>